name: "Setup Python Environment"
description: "Install uv, set up Python, and install project dependencies"

inputs:
  python-version:
    description: "Python version to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        uv venv
        uv pip install poetry
        uv run poetry install
